# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    #driver: "imagick"

    twig:
        mode: lazy

    filter_sets:

        scale:
            filters:
                scale:
                    dim: [ 100, 100 ]

        thumbnail:
            filters:
                thumbnail:
                    size: [ 100, 100 ]
                    mode: outbound
                    allow_upscale: true

        miniature:
            quality: 75
            filters:
                thumbnail:
                    size: [ 600, 330 ]
                    mode: outbound
                    allow_upscale: true

        hero:
            quality: 75
            filters:
                scale:
                    dim: [ 1200, 1200 ]

        full:
            quality: 85
            filters:
                scale:
                    dim: [ 1200, 1200 ]

        portfolio:
            quality: 75
            filters:
                scale:
                    dim: [ 400, 400 ]

        squared_thumbnail_medium:
            quality: 75
            filters:
                thumbnail:
                    size: [300, 300]
                    mode: outbound
                    allow_upscale: true

        squared_thumbnail_small:
            quality: 75
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound
                    allow_upscale: true