vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:

        product_image:
            uri_prefix: /uploads/product
            upload_destination: '%kernel.project_dir%/public/uploads/product'
            namer: vich_uploader.namer_uniqid
