version: '3.9'

services:

###> nginx ###
    #nginx:
    #    image: nginx:1.22-alpine
    #    ports:
    #        - 89:80
    #    volumes:
    #        - ./:/code
    #        - ./nginx.conf:/etc/nginx/nginx.conf
###< nginx ###

###> php ###
    #php:
    #    build: .
    #    volumes:
    #        - ./:/code
###< php ###

###> doctrine/doctrine-bundle ###
    db:
        image: mysql:latest
        container_name: e-commerce-db
        environment:
            # 🚨 Changer si vous utilisez cette configuration en production
            MYSQL_ROOT_PASSWORD: password # ⬅︎ 🚨
            MYSQL_DATABASE: e-commerce
            MYSQL_USER: symfony # ⬅︎ 🚨
            MYSQL_PASSWORD: symfony # ⬅︎ 🚨
        ports:
            - "3306:3306"
        volumes:
            - data:/var/lib/mysql
        restart: always
###< doctrine/doctrine-bundle ###

###> phpmyadmin ###
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: e-commerce-phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: password # ⬅︎ 🚨
            UPLOAD_LIMIT: 20M
        ports:
            - 8890:80
        restart: always
###< phpmyadmin ###

###> symfony/mailer ###
    mailer:
        image: axllent/mailpit:latest
        container_name: e-commerce-mailer
        ports:
            - 1025:1025 #SMTP
            - 8025:8025 #Boite mail
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

volumes:
###> doctrine/doctrine-bundle ###
    data:
###< doctrine/doctrine-bundle ###
